config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :search_suggestions
  devise_for :users
  get 'home/index'
  get 'home/about'
  root 'home#index'
  resources :tasks
  get '/search' => 'tasks#search', :as => 'search_task'
  get '/pending' => 'tasks#pending', :as => 'pending_task'
  get '/completed' => 'tasks#completed', :as => 'completed_task'
  get '/autocomplete' => 'tasks#autocomplete', :as => 'autocomplete_task'
  get '/expired' => 'tasks#expired', :as => 'expired_task'
  get '/todaylist' => 'tasks#todaylist', :as => 'todaylist_task'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :user
	validates_presence_of :todo
	default_scope -> { order('priority ASC') }
	
	 mount_uploaders :avatars, AvatarUploader
  	serialize :avatars, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

        has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
        	
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :force_json, only: :autocomplete

  # GET /tasks or /tasks.json
  def index

    @user= current_user
    @tasks = @user.tasks.paginate(page: params[:page], per_page: 4).order(params[:sort])
    # binding pry
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  def pending
    @user= current_user
    @tasks = @user.tasks.all.where(:completed => false)
    @tasks=@tasks.all.where('due_date >= ?', Date.today)
  end

  def expired
     @user= current_user
     @tasks = @user.tasks.all.where('due_date< ?', Date.today)
     @tasks =@tasks.all.where(:completed => false)
  end

  # GET /tasks/1/edit
  def edit
      
  end
  def completed
    @user= current_user
    @tasks = @user.tasks.all.where(:completed => true)
  end

  def autocomplete
    @user= current_user
      @parameter = params[:search].downcase  
      @results = @user.tasks.all
  end
  def todaylist
    @user= current_user
    @tasks = @user.tasks.all.where(:due_date => Date.today)
  end

  def search
    if params[:search].present?  
      params[:search].strip!
      
       @user= current_user
      @parameter = params[:search].downcase  
      @results = @user.tasks.all.where("lower(todo) LIKE :search OR LOWER(category) LIKE :search", search: @parameter)  
      
    else  
      respond_to do |format|
        format.html { redirect_to tasks_path , notice: "No search found." }
        format.json { render :show, status: :created, location: @task }
      end
      # redirect_to(tasks_path, alert: "Empty field!") and return  
    end  
  end


  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        @user= current_user
        TaskMailerJob.perform_later(@user,@task)
        format.html { redirect_to @task, notice: "Task was successfully created" }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  
  

      


  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
     
      if params[:remove_attachment]=='1'
          @task.remove_avatars!
          @task.save
      end

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def force_json
      request.format = :json
    end
    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:todo, :category, :due_date, :priority, :user_id, {avatars: []}, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-autocomplete/1.3.5/jquery.easy-autocomplete.min.js"></script>

<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <div class="container-fluid">
     <%= link_to 'TODO APP', root_path, class:"navbar-brand text-light" %> 
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   
 <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <li class="nav-item">
        	<%if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Todays Tasks", todaylist_task_path,class:"nav-link text-light" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
           </li>

           <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
              Tasks
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <li><button class="dropdown-item" type="button"><%= link_to "View All Task", tasks_path,class:"nav-link text-dark" %></button></li>
            <!-- <li><button class="" type="button">Another action</button></li>
            <li><button class="dropdown-item" type="button">Something else here</button></li> -->
            


           <li class="dropdown-item">
            <%= link_to "Expired Tasks", expired_task_path,class:"nav-link text-dark" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
           </li>

          <li class="nav-item">
            <%= link_to "Pending Tasks", pending_task_path,class:"nav-link text-dark" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
           </li>
           <li class="nav-item">
            <%= link_to "Completed Task", completed_task_path,class:"nav-link text-dark" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
           </li>
           </ul>
            </div>

       		 <li class="nav-item">
          <%= link_to "Add Task",new_task_path,class:"nav-link text-light " %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
        </li>

        <li class="nav-item">
          <%= link_to "View All Task", tasks_path,class:"nav-link text-light" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
        </li>
            <li>
            <h3 class="nav-item text-light">Welcome <%=current_user.name%></h3>
           </li>
          <li>
        <!-- <div class="search align-right" , data-autocomplete="task/autocomplete_task_todo_tasks"> -->
          <div class="search align-right" input id="basics">
           <%= form_tag(search_task_path, :method => "get", class: 'navbar-form navbar-left ' ) do %>  
          <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Search Task", class: "form-control",id:"task_search" %> 
           <div class="input-group-btn">  

          <%= button_tag "search", :class => 'btn btn-primary fas fa-search',:name => nil%>  
          </div>

             </div>  </div>
          </li>

           <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Profile
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li class="nav-item">
            <%= link_to "Edit Account?", edit_user_registration_path,class:"nav-link text-dark" %>
           </li>
            <li class="nav-item">
             <%= link_to "Sign-Out", destroy_user_session_path, method: :delete, class:"nav-link text-dark" %>
            </li>
          </ul>
        </div>

          <% end %>

          <%else %>
          <li class="nav-item">
          <%= link_to "Sign-Up", new_user_registration_path,class:"nav-link text-light" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
        </li>
        <li class="nav-item">
          <%= link_to "Sign-In", new_user_session_path,class:"nav-link text-light" %>
          <!-- <a class="nav-link text-light" href="#">Link</a> -->
        </li>

        <% end %>
      </ul>
 



 </div></div></div>

<%= link_to "About", home_about_path, class:"nav-link text-light align-right" %></li></nav>

app/views/home/about.html.erb
<h3>All about ToDoApp</h3>

app/views/home/index.html.erb
<h1> Welcome to ToDoApp</h1>

<%if !user_signed_in? %>
<br>
<%= link_to "Login to continue..", user_session_path, class:"nav-link "%>
<br>
<h3>New User? </h3>
<br>
<%= link_to "Create new Account", new_user_registration_path,class:"nav-link" %>
<br>
<%else%>
<div class="card" style="width: 18rem;">
	<div class="card-img-top">
	<%=image_tag("tick.jpg") %>
	</div>
<h5 class="card-title">
<%= link_to "Todays Task" , todaylist_task_path, class:"card-link" %>
</div>
<%end%>
<!-- <div class="float-sm-end">
<%=image_tag("tick.jpg") %>
</div> -->

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <#%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
    <!-- <#%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> -->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">




    <title>ToDo App!</title>
  </head>
  <body>
    <%= render 'home/header' %>

    <div class="container">
        <% if notice %>
        <%= render 'layouts/alerts'%>
        <%end%>
        <br>
    <h1>    <%= yield %></h1>
  </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field ">
      <%= form.label :Task_completed? %>
      <%= form.select :completed ,[false,true] %>
  </div>

  
  <div class="field ">
    <%= form.label :todo %>
    <%= form.text_field :todo %>
  </div>

  <div class="field form-group " >
    <%= form.label :category %>
  
    <%= form.select :category, ["work", "study", "shopping","personal","no category"] %>

  </div>
 

  <div class="field form-group">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field form-group">
    <%= form.label :priority %>
    <%= form.number_field :priority , min: 1%>
  </div>

  <div class="field form-group">
    <%= form.label :Add_images %>
    <%= form.file_field :avatars, multiple: true  %>
  </div>


  
  <% if @task.avatars? %>
  <ul>
    <% @task.avatars.each do |avatar| %>
    <%= image_tag(avatar.url)%>
    
  </ul>
    <br>
  <% end %>
     <ul>
      <p class="font-weight-bold">
        <%= check_box_tag (:remove_attachment)%> Remove Images
      </p>
  </ul>


  <%end%>
  

  <div class="field form-group visually-hidden ">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :task_user_id, class:"form-control" , value:current_user.id%>
  </div>

 <div class="field form-group">
  <!-- # <#%= form.text_field :signature, as: :hidden, class: 'signature_pad_input' %> -->
     <input name="signature" type="hidden" value="signature">
  <div class="signature_pad text-center">
    <div class="signature_pad_body">
      <canvas></canvas>
    </div>
    <div class="signature_pad_footer">
      <div class="text-muted">Sign above</div>
     <!--  <button type="button" class="btn btn-default signature_pad_clear">Clear</button>
      <#%= form.button :submit, 'Save', class: 'btn btn-success signature_pad_save'  %>
    </div> -->
  </div>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>

 
<% end %>
</form>

app/views/tasks/_taskformpartial.html.erb
<table  class="table table-dark table-striped">
  <thead>
    <tr>
      <th><%= link_to "Todo", :sort => "todo" %></th>
      <th><%= link_to "Category", :sort => "category" %></th>
      <th><%= link_to "Due date", :sort => "due_date" %></th>
      <th><%= link_to "Priority", :sort => "priority" %></th>
      <th><%= link_to "Status", :sort => "completed" %></th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.todo %></td>
        <td><%= task.category %></td>
        <td><%= task.due_date.strftime("%B %e, %Y") %></td>
        <td><%= task.priority %></td>
         <%if task.completed? %>
        <td>Completed</td>
        <%elsif task.due_date< Date.today && task.completed==false %>
        <td>Expired</td>
        <%else%>
        <td>Not Completed</td>
        <%end%>
        <!-- <td><%= task.user_id %></td> -->
        <td><%= link_to 'View', task %></td>
        <!-- <% if task.user == current_user%> -->
        <td><%= link_to 'Completed ?', edit_task_path(task) %></td>
        <td><%= link_to 'delete?', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%else%>
        <td></td>
        <td></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/completed.html.erb
<p id="notice"><%= notice %></p>


<h1 align="center">Completed Tasks</h1>

<%= render 'taskformpartial', task: @task %> 


<%= link_to 'Back', tasks_path %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/expired.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Expired Task</h1>

<%= render 'taskformpartial', task: @task %> 

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">All Tasks</h1>

 <%= render 'taskformpartial', task: @task %> 

<h4 align="center"><%= will_paginate @tasks %> </h4>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/pending.html.erb
<p id="notice"><%= notice %></p>
<h1 align="center">Task to do</h1>
<%= render 'taskformpartial', task: @task %> 

<%= link_to 'Back', tasks_path %>

app/views/tasks/search.html.erb
<h3>Search Result</h3>  
  <% @results.each do |result| %> 
    	  <% if result.todo.blank? %>
    	  no such task
    	  <%else%>
        task : <%= result.todo %><br> 
        <% if result.completed %>
        	completed!!
        <%else%>
        	Not Completed!!
        <%end  %><br>
        category : <%= result.category%> <br>
        due date : <%= result.due_date.strftime("%B %e, %Y") %> <br>
        <%= link_to 'Edit', edit_task_path(result) %> 
        <hr>
        <% end %>
    <% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo:</strong>
  <%= @task.todo %>
</p>

<p>
  <strong>Category:</strong>
  <%= @task.category %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date.strftime("%B %e, %Y") %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>


<% if @task.avatars? %>
  <ul>
    <% @task.avatars.each do |attachment| %>
       
        <%= link_to(image_tag(attachment.url, alt: 'Image')) %>
        <%= hidden_field :task, :attachments, multiple: true, value: attachment.identifier %>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Edit', edit_task_path(@task) %> 
<%= link_to 'Back', tasks_path %>

app/views/tasks/todaylist.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Today's Task</h1>

<%= render 'taskformpartial', task: @task %> 

<%= link_to 'Back', tasks_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>